---
- name: Install additional system tools.
  ansible.builtin.yum:
    name: 
      - setools
      - policycoreutils-python-utils
      - cockpit
      - tmux
      - aide
      - vim
      - bash-completion
    state: latest
  
- name: Start and enable services defined in the "services" variable.
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ services }}"

- name: Read the state of services
  ansible.builtin.service_facts:
