---
- name: "Ensure sudo is installed"
  ansible.builtin.package:
    name: sudo
    state: present
  when: rhel9cis_rule_5_2_1


- name: "Ensure sudo commands use pty"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "Defaults    use_pty"
    validate: '/usr/sbin/visudo -cf %s'
  when: rhel9cis_rule_5_2_2

- name: "Ensure sudo log file exists"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults    logfile='
    line: 'Defaults    logfile="{{ rhel9cis_sudolog_location }}"'
    validate: '/usr/sbin/visudo -cf %s'
  when: rhel9cis_rule_5_2_3

- name: "Ensure users must provide password for escalation"
  block:
    - name: "Ensure users must provide password for escalation | Discover accts with NOPASSWD"
      ansible.builtin.shell: grep -Ei '(nopasswd)' /etc/sudoers /etc/sudoers.d/* | cut -d':' -f1
      become: true
      changed_when: false
      failed_when: false
      register: discovered_nopasswd_sudoers

    - name: "Ensure users must provide password for escalation | Remove nopasswd for accounts not excluded"
      when: discovered_nopasswd_sudoers.stdout | length > 0
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^((?!#|{% for name in rhel9cis_sudoers_exclude_nopasswd_list %}{{ name }}{% if not loop.last -%}|{%- endif -%}{% endfor %}).*)NOPASSWD(.*)'
        replace: '\1PASSWD\2'
        validate: '/usr/sbin/visudo -cf %s'
      loop: "{{ discovered_nopasswd_sudoers.stdout_lines }}"
  when: rhel9cis_rule_5_2_4

- name: "Ensure re-authentication for privilege escalation is not disabled globally"
  block:
    - name: "Ensure re-authentication for privilege escalation is not disabled globally"
      ansible.builtin.shell: grep -Ei '(!authenticate)' /etc/sudoers /etc/sudoers.d/* | cut -d':' -f1
      become: true
      changed_when: false
      failed_when: false
      register: discovered_priv_reauth

    - name: "Ensure re-authentication for privilege escalation is not disabled globally"
      when: discovered_priv_reauth.stdout | length > 0
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^([^#].*)!authenticate(.*)'
        replace: '\1authenticate\2'
        validate: '/usr/sbin/visudo -cf %s'
      loop: "{{ discovered_priv_reauth.stdout_lines }}"
  when: rhel9cis_rule_5_2_5

- name: "Ensure sudo authentication timeout is configured correctly"
  block:
    - name: "Ensure sudo authentication timeout is configured correctly | Get files with timeout set"
      ansible.builtin.shell: grep -is 'timestamp_timeout' /etc/sudoers /etc/sudoers.d/* | cut -d":" -f1 | uniq | sort
      changed_when: false
      failed_when: false
      register: discovered_sudo_timeout_files

    - name: "Ensure sudo authentication timeout is configured correctly | Set value if no results"
      when: discovered_sudo_timeout_files.stdout | length == 0
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: 'Defaults timestamp_timeout='
        line: "Defaults timestamp_timeout={{ rhel9cis_sudo_timestamp_timeout }}"
        validate: '/usr/sbin/visudo -cf %s'

    - name: "Ensure sudo authentication timeout is configured correctly | Set value if has results"
      when: discovered_sudo_timeout_files.stdout | length > 0
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: 'timestamp_timeout=(\d+)'
        replace: "timestamp_timeout={{ rhel9cis_sudo_timestamp_timeout }}"
        validate: '/usr/sbin/visudo -cf %s'
      loop: "{{ discovered_sudo_timeout_files.stdout_lines }}"
  when: rhel9cis_rule_5_2_6

- name: "Ensure access to the su command is restricted"
  block:
    - name: "Ensure access to the su command is restricted | Ensure sugroup exists"
      ansible.builtin.group:
        name: "{{ rhel9cis_sugroup }}"
        state: present
      register: discovered_sugroup

    - name: "Ensure access to the su command is restricted | remove users from group"
      ansible.builtin.lineinfile:
        path: /etc/group
        regexp: '^{{ rhel9cis_sugroup }}(:.:.*:).*$'
        line: '{{ rhel9cis_sugroup }}\g<1>'
        backrefs: true

    - name: "Ensure access to the su command is restricted | Setting pam_wheel to use_uid"
      ansible.builtin.lineinfile:
        path: /etc/pam.d/su
        regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
        line: 'auth            required        pam_wheel.so use_uid group={{ rhel9cis_sugroup }}'
  when: rhel9cis_rule_5_2_7