---
ssh_allow:
### VPN networks ###
  - 172.18.199.0/24
  - 172.18.198.0/24
  - 172.18.200.0/24

cockpit_allow:
### VPN networks ###
  - 172.18.199.0/24
  - 172.18.198.0/24
  - 172.18.200.0/24

echo_request_allow:
### VPN networks ###
  - 172.18.199.0/24
  - 172.18.198.0/24
  - 172.18.200.0/24

echo_reply_allow:
### VPN networks ###
  - 172.18.199.0/24
  - 172.18.198.0/24
  - 172.18.200.0/24